version: "3.9"
services:
  api:
    restart: always
    build: ./server
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8080:8080"
  postgres:
    restart: always
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  # nginx:
  #   restart: always
  #   build: ./nginx
  #   depends_on:
  #     - api
  #   ports:
  #     - "80:80"
