CREATE TABLE IF NOT EXISTS cooks (
  id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  created TIMESTAMP NOT NULL,
  description VARCHAR(512) NOT NULL
);

CREATE TABLE IF NOT EXISTS readings (
  id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  timestamp TIMESTAMP NOT NULL,
  uptime INTEGER NOT NULL,
  meat_temp REAL NOT NULL,
  smoke_temp REAL NOT NULL,
  cook_id INT,
  CONSTRAINT fk_cook FOREIGN KEY(cook_id) REFERENCES cooks(id)
);
